#!/usr/bin/env zsh
# vim: set filetype=zsh

# Add more dirs to PATH
if [[ ! "${PATH}" == *:.* ]]; then
    export PATH="${PATH}:."
fi
for dir in bin .bin .local/bin; do
    if [[ ! "${PATH}" == *${HOME}/${dir}* ]]; then
        export PATH="${HOME}/${dir}:${PATH}"
    fi
done

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1

# Set the system-wide editor
export EDITOR=vim

# Set XDG_CONFIG_HOME
export XDG_CONFIG_HOME="${HOME}/.config"

# Set the GPG_TTY to the current TTY
export GPG_TTY=${TTY}

# FZF
export FZF_DEFAULT_COMMAND='fdfind . $HOME'
export FZF_DEFAULT_OPTS="--bind 'ctrl-v:execute(vim {})+abort,?:toggle-preview,alt-a:select-all,alt-d:deselect-all' --tiebreak=index --cycle --preview-window right:50%:border:wrap"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color=dark,fg:7,bg:-1,hl:5,fg+:15,bg+:8,hl+:13,info:2,prompt:4,pointer:1,marker:3,spinner:4,header:4"
export FZF_CTRL_R_OPTS="--layout=reverse --preview-window hidden"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fdfind -t d . $HOME"

# Zsh
export HISTORY_IGNORE="(ls|cat|AWS|SECRET)"
