# vim: foldmethod=marker
# Oh-My-Zsh {{{1
export ZSH="${HOME}/.oh-my-zsh"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

plugins=(
    aws
    colored-man-pages
    docker
    # fast-syntax-highlighting
    git
    helm
    #kubectl
    terraform
    # vi-mode
    you-should-use
    zsh-autosuggestions
    zsh-completions
    autoupdate
    # fzf-tab # fzf-tab should be the last plugin to bind "^I"
)

# Settings that must be applid before loading Oh-My-Zsh {{{2

# Set the theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Use case-sensitive completion
CASE_SENSITIVE="true"

# Fix slow paste
DISABLE_MAGIC_FUNCTIONS=true

# }}}

# Load oh-my-zsh
source "${ZSH}/oh-my-zsh.sh"

# ZSH {{{1

# Apply sensisble zsh settings
source ~/dotfiles/zsh/zshopt

# Bind C+Space to accept the current suggestion
bindkey '^ ' autosuggest-accept

# Set the default umask
umask 022

# OSTYPE specific settings
case "${OSTYPE}" in
    linux*)
        if (( $+commands[setxkbmap] )); then
            setxkbmap -option caps:escape_shifted_capslock
            setxkbmap -option altwin:swap_lalt_lwin
        fi
        ;;
    *) ;;
esac

# Source files {{{2
# Load aliases
source ~/dotfiles/zsh/aliases.zsh

# Load functions
source ~/dotfiles/zsh/functions.zsh

# Apply FZF configuration
source ~/dotfiles/zsh/fzf.zsh

# Apply autoupdate configuration
source ~/dotfiles/zsh/autoupdate.zsh

# Load any extra settings
test -f ~/dotfiles/zsh/extras && source ~/dotfiles/zsh/extras

# Completion {{{2

# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'

# Only display targets tag for make command completion
zstyle ':completion:*:*:make::' tag-order 'targets variables'

# give a preview of commandline arguments when completing `kill`
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"

# Reload the completions (uncomment if zsh-completions don't work)
# autoload -U compinit && compinit

# To customize prompt, run `p10k configure` or edit ~/.oh-my-zsh/custom/p10k.zsh.
[[ ! -f ~/.oh-my-zsh/custom/p10k.zsh ]] || source ~/.oh-my-zsh/custom/p10k.zsh
